<?php

declare(strict_types=1);

namespace SubtitleToolbox\Parsers;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use SubtitleToolbox\Comment;
use SubtitleToolbox\Exceptions\ParsingException;
use SubtitleToolbox\Format;
use SubtitleToolbox\ReadOptions;
use SubtitleToolbox\Subtitle;
use SubtitleToolbox\SubtitleCue;
use SubtitleToolbox\Tests\Support\RealFiles;

class AssParserTest extends TestCase
{
    use RealFiles;


    private const EVENTS_HEADER = "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";


    private static function realFilesDir(): string
    {
        return "ass/real/";
    }


    private static function realFilesFormat(): Format
    {
        return Format::Ass;
    }


    public static function realFiles(): array
    {
        return [
            "Aegisub" => [
                "own_aegisub.ass", 7,
                [1.0, 3.5, ["<v Conductor>Good morning, everyone."]],
                [16.1, 18.0, ["<v Passenger><u>Thank you</u>, and <s>good night</s> good day."]],
            ],
            "FFmpeg" => [
                "own_ffmpeg.ass", 7,
                [0.5, 2.75, ["The bakery opens at six."]],
                [62.04, 65.96, ["Thank you for shopping with us"]],
            ],
            "Aegisub signs with CR LF" => [
                "own_signs_crlf.ass", 7,
                [1.0, 4.0, ["<v Reporter>Good evening. Here is the weather."]],
                [14.1, 17.3, ["<v Reporter>That's all <font color=\"#0080ff\">for<b> tonight</b></font>" .
                              "<b><font color=\"#00ff00\"> from</font></b><font color=\"#00ff00\"> us.</font>"]],
            ],
            "Aegisub named styles" => [
                "own_style_flags.ass", 6,
                [1.0, 3.0, ["<v Driver>Last stop is the depot."]],
                [12.7, 15.0, ["<i><b>Left</b></i><i> again</i><b><u><s> already</s></u></b>"]],
            ],
            "SSA v4.00" => [
                "own_ssa_v4.ssa", 5,
                [2.0, 5.0, ["<v Captain><b>The ferry leaves the harbour at nine.</b>"]],
                [14.5, 17.0, ["<v Captain><b><font color=\"#ff0000\">Mind the gap</font> when you board.</b>"]],
            ],
        ];
    }


    #[DataProvider("realFiles")]
    public function testRealFileParses(string $file, int $cueCount, array $first, array $last): void
    {
        $cues = $this->parseFile($file)->getCues();

        $this->assertSame($cueCount, count($cues));
        $this->assertSame($first, [$cues[0]->getStart(), $cues[0]->getEnd(), $cues[0]->getLines()]);
        $this->assertSame($last, [end($cues)->getStart(), end($cues)->getEnd(), end($cues)->getLines()]);
    }


    public function testAegisubFileKeepsHeaderStylesAndComments(): void
    {
        $subtitle = $this->parseFile("own_aegisub.ass");
        $data     = $subtitle->findFormatData("ass");

        $this->assertSame("Morning train to the coast", $subtitle->findMetadata(Subtitle::METADATA_TITLE));
        $this->assertSame(["; Script generated by Aegisub 3.2.2", "; http://www.aegisub.org/"], $data["scriptInfoComments"]);
        $this->assertSame("1920", $data["scriptInfo"]["PlayResX"]);
        $this->assertArrayNotHasKey("Title", $data["scriptInfo"]);
        $this->assertSame(["Script Info", "Aegisub Project Garbage", "V4+ Styles", "Events"], $data["sectionOrder"]);
        $this->assertSame("Last Style Storage: Default", $data["sections"]["Aegisub Project Garbage"][0]);
        $this->assertSame(["Default", "Top", "Karaoke"], array_column($data["styles"], "Name"));
        $this->assertSame("Verdana", $data["styles"][2]["Fontname"]);
        $this->assertEquals(
            [
                new Comment("{\\r\\t(\$start,\$end,\\fscx120\\fscy120)\\t(\$end,\$end,\\fscx100\\fscy100)}", 0),
                new Comment("Check the platform number against the station sign", 2),
                new Comment("End of the station scene", 7),
            ],
            $subtitle->getComments()
        );
    }


    public function testAegisubFileConvertsOverrideTagsAndKaraoke(): void
    {
        $cues = $this->parseFile("own_aegisub.ass")->getCues();

        $this->assertSame(["<v Conductor>The train to the coast", "leaves from platform four."], $cues[1]->getLines());
        $this->assertSame(["Platform 4: <font color=\"#ffd700\">Coast Express</font>"], $cues[3]->getLines());
        $this->assertSame(8, $cues[3]->getAlignment());
        $this->assertSame(
            ["<b><00:00:13.500>The <00:00:13.900>train <00:00:14.250>leaves <00:00:14.750>at <00:00:15.350>noon</b>"],
            $cues[5]->getLines()
        );
        $this->assertSame(
            ["Layer" => "0", "Style" => "Default", "Name" => "Passenger", "MarginL" => "0", "MarginR" => "0", "MarginV" => "0", "Effect" => ""],
            $cues[2]->findFormatData("ass")["fields"]
        );
        $this->assertSame("{\\i1}Is it on time{\\i0} today?", $cues[2]->findFormatData("ass")["text"]);
    }


    public function testSignsFileSortsCuesAndSkipsDrawingsAndUnknownTags(): void
    {
        $subtitle = $this->parseFile("own_signs_crlf.ass");
        $cues     = $subtitle->getCues();

        $this->assertSame(["<v Reporter>Clouds move in from the west during the night."], $cues[1]->getLines());
        $this->assertSame(["SUNNY", "25 °C"], $cues[2]->getLines());
        $this->assertSame("1", $cues[2]->findFormatData("ass")["fields"]["Layer"]);
        $this->assertSame([], $cues[3]->getLines());
        $this->assertSame(7, $cues[3]->getAlignment());
        $this->assertSame(["<v Reporter>Expect light rain,\u{00A0}mostly after 10\u{00A0}pm."], $cues[4]->getLines());
        $this->assertSame(["<b><i>Tomorrow:</i></b> dry and windy"], $cues[5]->getLines());

        $sections = $subtitle->findFormatData("ass")["sections"];
        $this->assertSame("fontname: WeatherSans_0.ttf", $sections["Fonts"][0]);
        $this->assertSame("filename: sun.png", $sections["Graphics"][0]);
        $this->assertSame(3, count($sections["Graphics"]));
    }


    public function testSsaFileReadsMarkedColumnAndLegacyAlignment(): void
    {
        $subtitle = $this->parseFile("own_ssa_v4.ssa");
        $cues     = $subtitle->getCues();
        $data     = $subtitle->findFormatData("ass");

        $this->assertSame("V4 Styles", $data["stylesSection"]);
        $this->assertSame(AssFormatLines::SSA_EVENT_FORMAT, $data["eventFormat"]);
        $this->assertSame("-2147483640", $data["styles"][0]["BackColour"]);
        $this->assertSame(8, $cues[1]->getAlignment());
        $this->assertSame("Marked=1", $cues[2]->findFormatData("ass")["fields"]["Marked"]);
        $this->assertSame("!Effect", $cues[3]->findFormatData("ass")["fields"]["Effect"]);
        $this->assertEquals([new Comment("Timetable section", 1)], $subtitle->getComments());
    }


    public function testStyleFlagsAndAlignmentApplyToTheCues(): void
    {
        $cues = $this->parseFile("own_style_flags.ass")->getCues();

        $this->assertSame([
            [["<v Driver>Last stop is the depot."], null],
            [["<i>I should have taken the earlier bus.</i>"], 8],
            [["<i>Maybe the driver</i> knows a shortcut."], 2],
            [["<b><u><s>Depot closed for repairs</s></u></b>"], 7],
            [["The bus turns left at the bridge."], null],
            [["<i><b>Left</b></i><i> again</i><b><u><s> already</s></u></b>"], 8],
        ], array_map(fn (SubtitleCue $cue): array => [$cue->getLines(), $cue->getAlignment()], $cues));
    }


    public function testStyleItalicsAndAlignmentReachSubRip(): void
    {
        $this->assertStringContainsString(
            "00:00:03,200 --> 00:00:05,400\n{\\an8}<i>I should have taken the earlier bus.</i>\n",
            $this->parseFile("own_style_flags.ass")->toString(Format::SubRip)
        );
    }


    public function testStylesAfterTheEventsSectionStillApply(): void
    {
        $cue = $this->parseEvents(
            self::EVENTS_HEADER . "Dialogue: 0,0:00:01.00,0:00:02.00,*Thoughts,,0,0,0,,Hmm\n\n" .
            "[V4+ Styles]\nFormat: Name, Italic, Alignment\nStyle: Thoughts,-1,9\n"
        )->getCues()[0];

        $this->assertSame([["<i>Hmm</i>"], 9], [$cue->getLines(), $cue->getAlignment()]);
    }


    public function testSsaStyleUsesTheLegacyAlignmentCode(): void
    {
        $cue = $this->parseEvents(
            "[V4 Styles]\nFormat: Name, Bold, Italic, Alignment\nStyle: Default,-1,0,6\n\n" .
            "[Events]\nFormat: Marked, Start, End, Style, Text\nDialogue: Marked=0,0:00:01.00,0:00:02.00,Other,Hello\n"
        )->getCues()[0];

        $this->assertSame([["<b>Hello</b>"], 8], [$cue->getLines(), $cue->getAlignment()]);
    }


    public function testCommentEventStaysBeforeItsEventWhenTheEventsAreOutOfTimeOrder(): void
    {
        $subtitle = $this->parseFile("own_comment_before_earlier_event.ass");

        $this->assertSame(["The door opens.", "The shop is open.", "The shop closes."], array_map(fn (SubtitleCue $cue) => $cue->getText(), $subtitle->getCues()));
        $this->assertEquals([
            new Comment("The door opens before the shop", 0),
            new Comment("The shop opens at nine", 1),
            new Comment("End of the shop scene", 3),
        ], $subtitle->getComments());
    }


    public function testColumnsAreMappedByName(): void
    {
        $cue = $this->parseEvents(
            "[Events]\nFormat: Name, End, Start, Style, Text\nDialogue: Ann,0:00:05.00,0:00:04.00,Default,Hi, you\n"
        )->getCues()[0];

        $this->assertSame([4.0, 5.0, ["<v Ann>Hi, you"]], [$cue->getStart(), $cue->getEnd(), $cue->getLines()]);
    }


    public static function overrideTags(): array
    {
        return [
            "bold and italic"            => ["{\\b1}a{\\b0} {\\i1}b{\\i0}", ["<b>a</b> <i>b</i>"]],
            "open tag closes at the end" => ["{\\u1}a", ["<u>a</u>"]],
            "empty value resets"         => ["{\\s1}a{\\s}b", ["<s>a</s>b"]],
            "weight is no core markup"   => ["{\\b700}a", ["a"]],
            "BGR colour"                 => ["{\\c&H0000FF&}red", ["<font color=\"#ff0000\">red</font>"]],
            "primary colour"             => ["{\\1c&HFF0000&}blue", ["<font color=\"#0000ff\">blue</font>"]],
            "short colour"               => ["{\\c&HFF&}red", ["<font color=\"#ff0000\">red</font>"]],
            "colour reset"               => ["{\\c&H00FF00&}a{\\c}b", ["<font color=\"#00ff00\">a</font>b"]],
            "border colour is dropped"   => ["{\\3c&H0000FF&}a", ["a"]],
            "tags nest"                  => ["{\\b1}a{\\i1}b{\\b0}c{\\i0}d", ["<b>a<i>b</i></b><i>c</i>d"]],
            "reset closes all"           => ["{\\b1\\i1}a{\\r}b", ["<b><i>a</i></b>b"]],
            "reset to style"             => ["{\\b1}a{\\rSign}b", ["<b>a</b>b"]],
            "animation is skipped"       => ["{\\t(0,500,\\b1\\1c&H0000FF&)}a", ["a"]],
            "comment block"              => ["a{note}b", ["ab"]],
            "drawing"                    => ["{\\p1}m 0 0 l 10 0{\\p0}text", ["text"]],
            "escaped text"               => ["1 < 2 & 3 > 2", ["1 &lt; 2 &amp; 3 &gt; 2"]],
            "hard break"                 => ["a\\Nb", ["a", "b"]],
            "soft break"                 => ["a\\nb", ["a b"]],
            "hard space"                 => ["a\\hb", ["a\u{00A0}b"]],
        ];
    }


    #[DataProvider("overrideTags")]
    public function testOverrideTagsBecomeCoreMarkup(string $text, array $lines): void
    {
        $this->assertSame($lines, $this->parseText($text)->getLines());
    }


    public static function alignments(): array
    {
        return [
            "numpad"            => ["{\\an7}a", 7],
            "first tag wins"    => ["{\\an7}a{\\an3}b", 7],
            "legacy top center" => ["{\\a6}a", 8],
            "legacy middle"     => ["{\\a9}a", 4],
            "invalid legacy"    => ["{\\a4}a", null],
            "none"              => ["a", null],
        ];
    }


    #[DataProvider("alignments")]
    public function testAlignmentTagsSetTheAlignment(string $text, ?int $alignment): void
    {
        $this->assertSame($alignment, $this->parseText($text)->getAlignment());
    }


    public function testKaraokeTagsBecomeWordTimestamps(): void
    {
        $cue = $this->parseEvents(self::EVENTS_HEADER . "Dialogue: 0,0:01:00.00,0:01:05.00,Default,,0,0,0,,{\\k50}Ka{\\kf25}ra{\\K100}o{\\ko12.5}ke\n")->getCues()[0];

        $this->assertSame(["<00:01:00.000>Ka<00:01:00.500>ra<00:01:00.750>o<00:01:01.750>ke"], $cue->getLines());
    }


    public function testSoftBreakIsAHardBreakInWrapStyle2(): void
    {
        $cue = $this->parseEvents("[Script Info]\nWrapStyle: 2\n\n" . self::EVENTS_HEADER . "Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,a\\nb\n")->getCues()[0];

        $this->assertSame(["a", "b"], $cue->getLines());
    }


    public function testNameBecomesSpeakerOnTheFirstTextLine(): void
    {
        $cue = $this->parseEvents(self::EVENTS_HEADER . "Dialogue: 0,0:00:01.00,0:00:02.00,Default,A<B,0,0,0,,{\\an8}\\N  Hi\n")->getCues()[0];

        $this->assertSame(["<v A&lt;B>Hi"], $cue->getLines());
    }


    public function testWindows1252FileReadAsUtf8KeepsItsLinesAndSpeaker(): void
    {
        $lines = array_map(
            fn (SubtitleCue $cue): array => array_map(fn (string $line): string => iconv("Windows-1252", "UTF-8", $line), $cue->getLines()),
            Subtitle::fromString(file_get_contents(__DIR__ . "/../files/ass/own_windows_1252.ass"), Format::Ass, new ReadOptions(encoding: "UTF-8"))->getCues()
        );

        $this->assertSame([
            ["<v Hélène>Le café ouvre à sept heures."],
            ["<i>Crème brûlée</i>", "à 4 €"],
            ["<v Hélène>See you tomorrow."],
        ], $lines);
    }


    public function testTimesAcceptOneToThreeFractionDigits(): void
    {
        $cue = $this->parseEvents(self::EVENTS_HEADER . "Dialogue: 0,10:00:01.5,10:00:02.125,Default,,0,0,0,,a\n")->getCues()[0];

        $this->assertSame([36001.5, 36002.125], [$cue->getStart(), $cue->getEnd()]);
    }


    public function testEventsWithoutFormatLineUseTheDefaultColumns(): void
    {
        $subtitle = $this->parseEvents("[Script Info]\nScriptType: v4.00\n\n[Events]\nDialogue: Marked=0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hi\n");

        $this->assertSame(["Hi"], $subtitle->getCues()[0]->getLines());
        $this->assertSame(AssFormatLines::SSA_EVENT_FORMAT, $subtitle->findFormatData("ass")["eventFormat"]);
    }


    public static function invalidFiles(): array
    {
        return [
            "no events section"  => ["[V4+ Styles]\nFormat: Name\n"],
            "too few fields"     => [self::EVENTS_HEADER . "Dialogue: 0,0:00:01.00,0:00:02.00\n"],
            "invalid time"       => [self::EVENTS_HEADER . "Dialogue: 0,1.00,0:00:02.00,Default,,0,0,0,,a\n"],
            "no text column"     => ["[Events]\nFormat: Start, End\nDialogue: 0:00:01.00,0:00:02.00\n"],
        ];
    }


    #[DataProvider("invalidFiles")]
    public function testInvalidFileThrows(string $content): void
    {
        $this->expectException(ParsingException::class);

        $this->parseEvents($content);
    }


    public function testScriptInfoWithoutEventsGivesAnEmptySubtitleInBothModes(): void
    {
        $content = file_get_contents(__DIR__ . "/../files/ass/real/own_script_info_only.ass");

        foreach ([false, true] as $lenient) {
            $subtitle = Subtitle::fromString($content, Format::Ass, new ReadOptions(lenient: $lenient));
            $data     = $subtitle->findFormatData("ass");

            $this->assertSame([], $subtitle->getCues());
            $this->assertSame([], $subtitle->getParseWarnings());
            $this->assertSame("New subtitles", $subtitle->findMetadata(Subtitle::METADATA_TITLE));
            $this->assertSame("1920", $data["scriptInfo"]["PlayResX"]);
            $this->assertSame(["Script Info", "V4+ Styles"], $data["sectionOrder"]);
            $this->assertSame(["Default"], array_column($data["styles"], "Name"));
        }
        $this->assertStringContainsString("Style: Default,Arial,48,", $subtitle->toString(Format::Ass));
    }


    public function testContentWithoutScriptInfoAndEventsStillThrows(): void
    {
        $this->expectException(ParsingException::class);
        $this->expectExceptionMessage("The subtitle has no [Events] section.");
        (new AssParser())->parse("[V4+ Styles]\nFormat: Name, Fontname\nStyle: Default,Arial\n", new ReadOptions(lenient: true));
    }


    private function parseEvents(string $content): Subtitle
    {
        return (new AssParser())->parse($content, new ReadOptions());
    }


    private function parseText(string $text): SubtitleCue
    {
        return $this->parseEvents(self::EVENTS_HEADER . "Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,$text\n")->getCues()[0];
    }


    public function testABadEventTimeThrowsWithItsLineNumber(): void
    {
        // Line 11 of the file is a short event, which throws first. Without it, line 12 holds the bad time.
        $content = str_replace("Dialogue: 0,0:00:04.00,0:00:06.00,Default\r\n", "\r\n",
                               file_get_contents(__DIR__ . "/../files/lenient/broken_events.ass"));

        try {
            (new AssParser())->parse($content, new ReadOptions());
            $this->fail("No exception");
        } catch (ParsingException $exception) {
            $this->assertSame(12, $exception->getLineNumber());
            $this->assertStringEndsWith("The time \"0:00:0x.00\" is not valid. (line 12)", $exception->getMessage());
        }
    }
}
